version: '3.9'
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pushfight
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pushfight_api