# Shared properties
---
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    contexts: h2
  devtools:
    livereload:
      enabled: false

pushfight:
  security:
    clients-json: '[]'
    signing-key: ''

# Local Postgres properties
---
spring:
  profiles: local-postgres
  datasource:
    url: jdbc:postgresql://localhost/pushfight_api
    username: pushfight
    password: password
  liquibase:
    contexts: postgres

# Production properties
---

spring:
  profiles: production
  liquibase:
    contexts: postgres
